---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/release-drafter.yaml@v3.0.0
